import streamlit as st
import google.generativeai as genai
from googlesearch import search
from fpdf import FPDF
from PIL import Image
import datetime

# --- 1. CONFIG & UI STYLE (NO "AI" MENTION) ---
st.set_page_config(
    page_title="KSB Suite: Forensic Audit", 
    page_icon="⚖️", 
    layout="wide",
    initial_sidebar_state="collapsed"
)

# CSS: Professional 'Audit Firm' aesthetic
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;700&display=swap');
    
    .stApp {
        background-color: #f8fafc; /* Slate-50 */
        font-family: 'Plus Jakarta Sans', sans-serif;
    }
    
    /* Card Style: Clean Corporate Look */
    .audit-card {
        background: white;
        border: 1px solid #e2e8f0;
        border-radius: 12px;
        padding: 30px;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
        margin-bottom: 24px;
    }
    
    /* Typography */
    h1 { color: #0f172a; font-weight: 800; letter-spacing: -0.5px; }
    h2 { color: #334155; font-size: 1.2rem; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; }
    
    /* Inputs */
    .stTextInput>div>div>input, .stSelectbox>div>div>div {
        border-radius: 8px;
        border: 1px solid #cbd5e1;
    }
    
    /* Action Button: 'System' feel */
    .stButton>button {
        background-color: #0f172a; /* Slate-900 */
        color: white;
        border-radius: 8px;
        padding: 0.8rem 2rem;
        font-weight: 600;
        letter-spacing: 0.5px;
        border: none;
        width: 100%;
        transition: background 0.2s;
    }
    .stButton>button:hover {
        background-color: #1e293b;
    }
</style>
""", unsafe_allow_html=True)

# --- 2. DATA REFERENSI (Nice Classification) ---
FULL_CLASSES = [
    "Kelas 03 - Kosmetik, Pembersih, Parfum",
    "Kelas 05 - Farmasi & Obat-obatan",
    "Kelas 09 - Teknologi, Software, Elektronik",
    "Kelas 25 - Pakaian, Alas Kaki, Penutup Kepala",
    "Kelas 30 - Kopi, Teh, Makanan Pokok",
    "Kelas 32 - Minuman Non-Alkohol",
    "Kelas 35 - Jasa Periklanan & Toko (Retail)",
    "Kelas 41 - Jasa Pendidikan & Hiburan",
    "Kelas 43 - Jasa Restoran & Kafe",
    "Kelas 45 - Jasa Hukum & Keamanan",
    "Lainnya (Sistem akan mendeteksi otomatis)"
]

# --- 3. CORE LOGIC (SEARCH) ---
def legal_index_search(keyword):
    """Melakukan pencarian jejak digital pada index database pemerintah."""
    results = []
    # Query ke index publik (Legal & Safe)
    query = f'site:pdki-indonesia.dgip.go.id "{keyword}" OR {keyword}'
    try:
        for url in search(query, num_results=6, lang="id"):
            results.append(url)
    except:
        pass
    return results

# --- 4. PDF GENERATOR (TABLE FORMAT - EYE CATCHING) ---
class AuditPDF(FPDF):
    def header(self):
        # Header Biru Tua Profesional
        self.set_fill_color(15, 23, 42) # Slate-900
        self.rect(0, 0, 210, 40, 'F')
        
        self.set_font('Arial', 'B', 20)
        self.set_text_color(255, 255, 255)
        self.cell(0, 25, 'KSB SUITE: FORENSIC REPORT', 0, 1, 'C')
        
        self.set_font('Arial', '', 9)
        self.set_text_color(148, 163, 184) # Slate-400
        self.cell(0, -10, 'OFFICIAL TRADEMARK AUDIT DOCUMENT', 0, 1, 'C')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by KSB System V.6.0 | Confidential', 0, 0, 'C')

    def table_row(self, label, content, fill=False):
        # Fungsi helper untuk membuat baris tabel
        self.set_font('Arial', 'B', 10)
        self.set_fill_color(241, 245, 249) # Slate-100
        self.set_text_color(15, 23, 42)
        
        # Kolom Label
        x_start = self.get_x()
        y_start = self.get_y()
        
        self.cell(50, 10, label, 1, 0, 'L', True) # Header Kolom Kiri
        
        # Kolom Isi (Multi Cell untuk teks panjang)
        self.set_font('Arial', '', 10)
        self.set_xy(x_start + 50, y_start)
        
        # Simpan posisi Y sebelum menulis multicell
        self.multi_cell(140, 10, content, 1, 'L', fill)
        
        # Reset posisi untuk baris berikutnya (jika multicell nambah tinggi)
        # Sederhananya untuk demo ini kita pakai fixed height atau logic height sederhana
        # Di FPDF standar agak rumit auto-height tabel, kita gunakan ln() standar
        # Untuk "Eye Catching", kita pastikan konten bersih.

def create_professional_pdf(brand, cls, analysis_raw, risk_score):
    pdf = AuditPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # --- SECTION 1: CASE DETAILS (TABLE STYLE) ---
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, 'I. CASE IDENTIFICATION', 0, 1, 'L')
    pdf.ln(2)
    
    pdf.set_line_width(0.3)
    pdf.set_draw_color(203, 213, 225) # Slate-300
    
    # Row 1
    pdf.set_font('Arial', 'B', 10)
    pdf.set_fill_color(248, 250, 252)
    pdf.cell(50, 10, ' TARGET MARK', 1, 0, 'L', 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(140, 10, f' {brand.upper()}', 1, 1, 'L', 0)
    
    # Row 2
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(50, 10, ' CLASSIFICATION', 1, 0, 'L', 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(140, 10, f' {cls}', 1, 1, 'L', 0)
    
    # Row 3
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(50, 10, ' AUDIT DATE', 1, 0, 'L', 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(140, 10, f' {datetime.date.today()}', 1, 1, 'L', 0)
    
    pdf.ln(10)
    
    # --- SECTION 2: RISK ASSESSMENT (COLOR BOX) ---
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'II. RISK CALCULATOR', 0, 1, 'L')
    pdf.ln(2)
    
    # Warna berdasarkan risiko
    if "HIGH" in risk_score:
        pdf.set_fill_color(254, 226, 226) # Red-100
        pdf.set_text_color(185, 28, 28)   # Red-700
    elif "MEDIUM" in risk_score:
        pdf.set_fill_color(254, 243, 199) # Yellow-100
        pdf.set_text_color(180, 83, 9)    # Yellow-700
    else:
        pdf.set_fill_color(220, 252, 231) # Green-100
        pdf.set_text_color(21, 128, 61)   # Green-700
        
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(190, 15, f'STATUS: {risk_score}', 1, 1, 'C', 1)
    
    pdf.ln(10)
    
    # --- SECTION 3: FORENSIC FINDINGS (RAW TEXT FORMATTED) ---
    pdf.set_text_color(15, 23, 42) # Reset Color
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'III. FORENSIC MATRIX FINDINGS', 0, 1, 'L')
    pdf.ln(2)
    
    # Cleaning the raw text for PDF compatibility (Remove Emojis & Bold markdown)
    clean_text = analysis_raw.encode('latin-1', 'ignore').decode('latin-1')
    clean_text = clean_text.replace('**', '').replace('###', '').replace('|', '')
    
    # Display as a formal block
    pdf.set_font('Courier', '', 10) # Monospace for technical look
    pdf.set_fill_color(255, 255, 255)
    pdf.multi_cell(190, 6, clean_text, 1, 'L', 0)
    
    return pdf.output(dest='S').encode('latin-1')

# --- 5. SYSTEM LOGIC (NO "AI" MENTION IN PROMPT) ---
def run_system_audit(api_key, brand, cls, competitors, image_file=None):
    genai.configure(api_key=api_key)
    model = genai.GenerativeModel("gemini-2.5-flash")
    
    comp_data = "\n".join(competitors) if competitors else "No direct index matches found."
    
    # PROMPT DIREKAYASA UNTUK OUTPUT SEPERTI LAPORAN AUDITOR MANUSIA
    prompt = f"""
    ACT AS: Lead Intellectual Property Auditor.
    TASK: Perform a strict forensic audit on the trademark application below.
    LANGUAGE: Indonesian (Formal, Corporate Style).
    
    INPUT DATA:
    - Mark: "{brand}"
    - Class: {cls}
    - Visual Evidence: {"Attached" if image_file else "None"}
    - Database Findings: {comp_data}
    
    AUDIT PROTOCOLS (STRICTLY FOLLOW):
    1. Phonetic Check (Sound-alike test against findings or famous marks).
    2. Visual Check (Logo similarity / generic shapes).
    3. Conceptual Check (Translation / Meaning collisions).
    4. Distinctiveness Check (Is it descriptive/generic?).

    OUTPUT FORMAT REQURIEMENT (Do not use conversational filler):
    Provide the output in a clean layout suitable for a formal report.
    
    [SECTION 1: EXECUTIVE SUMMARY]
    (1 Sentence Verdict: APPROVED / REJECTED potential)

    [SECTION 2: DETAILED MATRIX]
    - Phonetic Analysis: [Details...]
    - Conceptual Analysis: [Details...]
    - Visual Analysis: [Details...]
    - Distinctiveness: [Details...]

    [SECTION 3: RECOMMENDATION]
    (Bullet points of tactical advice)

    [RISK LEVEL]
    (Write exactly one: HIGH RISK / MEDIUM RISK / LOW RISK)
    """
    
    inputs = [prompt]
    if image_file:
        img = Image.open(image_file)
        inputs.append(img)
    
    try:
        response = model.generate_content(inputs)
        return response.text
    except Exception as e:
        return f"System Audit Error: {str(e)}"

# --- 6. FRONTEND APPLICATION ---

# Header
st.markdown("""
<div style="margin-bottom: 30px; border-bottom: 1px solid #e2e8f0; padding-bottom: 20px;">
    <h1 style="margin:0;">KSB SUITE <span style="font-size:0.6em; background:#0f172a; color:white; padding:4px 8px; border-radius:6px; vertical-align:middle;">FORENSIC</span></h1>
    <p style="color:#64748b; font-size: 0.9rem; margin-top:5px;">Professional Trademark Audit System v6.0</p>
</div>
""", unsafe_allow_html=True)

# API Key Check (Silent)
api_key = st.secrets.get("GOOGLE_API_KEY")
if not api_key:
    st.error("⚠️ SYSTEM ALERT: Security Key not found in environment.")
    st.stop()

# Main Interface
with st.container():
    # Input Card
    st.markdown('<div class="audit-card">', unsafe_allow_html=True)
    c1, c2 = st.columns([2, 1])
    
    with c1:
        st.markdown("## 1. Subject Details")
        brand_name = st.text_input("Trademark Name", placeholder="e.g. KASHAFA")
        brand_class = st.selectbox("Nice Classification", FULL_CLASSES)
        
    with c2:
        st.markdown("## 2. Visual Evidence")
        upl_file = st.file_uploader("Upload Mark/Logo (Optional)", type=['png', 'jpg'])
        if upl_file:
            st.caption("File attached to audit case.")
            
    st.markdown('</div>', unsafe_allow_html=True)
    
    # Execution
    if st.button("INITIATE AUDIT PROTOCOL"):
        if not brand_name:
            st.warning("Input Required: Trademark Name")
        else:
            # 1. Scanning
            status_text = st.empty()
            progress = st.progress(0)
            
            status_text.markdown("**Scanning Federal Database Index...**")
            progress.progress(25)
            findings = legal_index_search(brand_name)
            
            # 2. Auditing
            status_text.markdown("**Running Forensic Analysis Algorithms...**")
            progress.progress(60)
            audit_text = run_system_audit(api_key, brand_name, brand_class, findings, upl_file)
            
            progress.progress(100)
            status_text.empty()
            progress.empty()
            
            # 3. Output
            st.markdown('<div class="audit-card" style="border-left: 5px solid #0f172a;">', unsafe_allow_html=True)
            st.markdown("## AUDIT FINDINGS")
            st.markdown("---")
            # Menampilkan hasil dengan rapi (tanpa tabel markdown yang mungkin pecah, text based report)
            st.markdown(audit_text)
            st.markdown('</div>', unsafe_allow_html=True)
            
            # 4. PDF Generation
            # Extract Risk Level from text
            risk_val = "LOW RISK"
            if "HIGH RISK" in audit_text: risk_val = "HIGH RISK"
            elif "MEDIUM RISK" in audit_text: risk_val = "MEDIUM RISK"
            
            pdf_data = create_professional_pdf(brand_name, brand_class, audit_text, risk_val)
            
            st.download_button(
                label="📥 EXPORT OFFICIAL REPORT (PDF)",
                data=pdf_data,
                file_name=f"AUDIT_REPORT_{brand_name.upper()}.pdf",
                mime="application/pdf",
                use_container_width=True
            )
